---
- name: Ensure the .ssh directory exists.
  file:
    path: "{{ lookup('env','HOME') }}/.ssh"
    state: directory
- name: Ensure the SSH client is configured.
  copy:
    src: files/ssh/config
    dest: "{{ lookup('env','HOME') }}/.ssh/config"
- name: Generate an ED25519 SSH key.
  community.crypto.openssh_keypair:
    comment: "{{ email_address }}"
    type: ed25519
    path: "{{ lookup('env','HOME') }}/.ssh/id_ed25519"
- name: Generate an RSA SSH key.
  community.crypto.openssh_keypair:
    comment: "{{ email_address }}"
    type: rsa
    size: 4096
    path: "{{ lookup('env','HOME') }}/.ssh/id_rsa"
# - name: Add SSH key to Github
#   command: gh ssh-key add ~/.ssh/id_ed25519.pub
