---
- name: Install Visual Studio Code extensions.
  command: "/Applications/Visual\\ Studio\\ Code.app/Contents/Resources/app/bin/code --install-extension {{ item }}"
  loop:
    - bazelbuild.vscode-bazel
    - davidanson.vscode-markdownlint
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - foxundermoon.shell-format
    - github.copilot
    - github.vscode-pull-request-github
    - golang.go
    - googlecloudtools.cloudcode
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-python.flake8
    - ms-python.isort
    - ms-python.python
    - ms-python.pylint
    - ms-python.vscode-pylance
    - ms-vscode.makefile-tools
    - ms-vscode-remote.remote-containers
    - redhat.vscode-commons
    - redhat.vscode-yaml
    - samuelcolvin.jinjahtml
    - snyk-security.snyk-vulnerability-scanner
    - valeryanm.vscode-phpsab
    - vscjava.vscode-java-pack
    - xdebug.php-debug
    - zxh404.vscode-proto3
- name: Ensure Visual Studio Code user directory exists.
  file:
    path: "{{ lookup('env','HOME') }}/Library/Application Support/Code/User"
    state: directory
- name: Install Visual Studio Code user settings.
  copy:
    src: files/visual-studio-code/settings.json
    dest: "{{ lookup('env','HOME') }}/Library/Application Support/Code/User/settings.json"
