---
- name: Install Visual Studio Code extensions.
  command: "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code --install-extension {{ item }}"
  loop:
    - bazelbuild.vscode-bazel
    - davidanson.vscode-markdownlint
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - felixfbecker.php-debug
    - foxundermoon.shell-format
    - github.vscode-pull-request-github
    - googlecloudtools.cloudcode
    - ikappas.phpcs
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-vscode.go
    - ms-vscode.makefile-tools
    - redhat.vscode-commons
    - redhat.vscode-yaml
    - samuelcolvin.jinjahtml
    - zxh404.vscode-proto3
- name: Install Visual Studio Code user settings.
  copy:
    content: "{{ settings | to_nice_json }}"
    dest: "{{ lookup('env','HOME') }}/Library/Application\ Support/Code/User/settings.json"
  vars:
    settings:
      cloudcode.enableMultiSkaffoldConfigsKey: true
      cloudcode.yaml.format.enable: true
      editor.bracketPairColorization.enabled: true
      editor.detectIndentation: false
      editor.formatOnSave: true
      editor.guides.bracketPairs: active
      files.insertFinalNewline: true
      files.trimTrailingWhitespace: true
      git.autofetch: true
      gitlens.gitCommands.closeOnFocusOut: true
      go.formatTool: goimports
      go.toolsManagement.autoUpdate: true
      go.useLanguageServer: true
      merge-conflict.diffViewPosition: Below
      python.languageServer: Pylance
      redhat.telemetry.enabled: false
      window.zoomLevel: 1
