---
- name: Install Visual Studio Code extensions.
  command: "/Applications/Visual\\ Studio\\ Code.app/Contents/Resources/app/bin/code --install-extension {{ item }}"
  loop:
    - bazelbuild.vscode-bazel
    - davidanson.vscode-markdownlint
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - foxundermoon.shell-format
    - github.vscode-pull-request-github
    - golang.go
    - googlecloudtools.cloudcode
    - ikappas.phpcs
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-vscode.makefile-tools
    - redhat.vscode-commons
    - redhat.vscode-yaml
    - samuelcolvin.jinjahtml
    - xdebug.php-debug
    - zxh404.vscode-proto3
- name: Ensure Visual Studio Code user directory exists.
  file:
    path: "{{ lookup('env','HOME') }}/Library/Application\\ Support/Code/User"
    state: directory
- name: Install Visual Studio Code user settings.
  copy:
    content: "{{ settings | to_nice_json }}"
    dest: "{{ lookup('env','HOME') }}/Library/Application\\ Support/Code/User/settings.json"
  vars:
    settings:
      cloudcode.enableMultiSkaffoldConfigsKey: true
      cloudcode.yaml.format.enable: true
      editor.bracketPairColorization.enabled: true
      editor.detectIndentation: false
      editor.formatOnSave: true
      editor.guides.bracketPairs: active
      files.insertFinalNewline: true
      files.trimTrailingWhitespace: true
      git.autofetch: true
      gitlens.gitCommands.closeOnFocusOut: true
      go.formatTool: goimports
      go.toolsManagement.autoUpdate: true
      go.useLanguageServer: true
      merge-conflict.diffViewPosition: Below
      python.languageServer: Pylance
      redhat.telemetry.enabled: false
      terminal.integrated.defaultProfile.osx: zsh
      window.zoomLevel: 1
